apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-dep
  labels:
    app: flask-service1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-service1
  template:
    metadata:
      labels:
        app: flask-service1
    spec:
      containers:
      - name: flask
        image: bcattaneo/flask-service1:v0
        ports:
        - containerPort: 5000
