apiVersion: v1
kind: Service
metadata:
  name: ucu-svc
  labels:
    app: ucu-service
spec:
  type: LoadBalancer 
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
  selector:
    app: ucu-service
